FROM golang:1.19.0-alpine3.16

COPY . /go/src/github.com/microservices-demo/catalogue
WORKDIR /go/src/github.com/microservices-demo/catalogue

RUN apk update && apk add --no-cache gcc libc-dev
RUN rm -f /go/src/github.com/microservices-demo/catalogue/go.sum
RUN go mod tidy && go mod vendor
RUN go test
RUN cd /go/src/github.com/microservices-demo/catalogue/cmd/cataloguesvc && go install

FROM alpine:3.16

WORKDIR /
EXPOSE 80
COPY --from=0 /go/bin/cataloguesvc /app
COPY images/ /images/

ARG BUILD_DATE
ARG BUILD_VERSION
ARG COMMIT

LABEL org.label-schema.vendor="Weaveworks" \
  org.label-schema.build-date="${BUILD_DATE}" \
  org.label-schema.version="${BUILD_VERSION}" \
  org.label-schema.name="Socks Shop: Catalogue" \
  org.label-schema.description="REST API for Catalogue service" \
  org.label-schema.url="https://github.com/cams7-tests/sockshop-catalogue" \
  org.label-schema.vcs-url="github.com/cams7-tests/sockshop-catalogue.git" \
  org.label-schema.vcs-ref="${COMMIT}" \
  org.label-schema.schema-version="1.0.3"

CMD ["/app", "-port=80"]
